---

- name: APT | Install apt-transport-https
  apt: >
    pkg=apt-transport-https
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: APT_KEY | Get APT key repository
  apt_key: url="{{ phalcon_apt_gpg_url }}"

- name: APT_REPOSITORY | Installs repository
  apt_repository: >
    repo="{{ phalcon_apt }}"

- name: Get PHP
  shell: php --version | grep -o '^PHP [[:digit:]]\.[[:digit:]]' | awk '{ print $NF }'
  register: phpversion
  failed_when: false
  changed_when: false

- block:

    - name: SET_FACT | Set php5-phalcon
      set_fact: phalcon_package='php5-phalcon'
      when: phpversion.stdout.find('5') != -1

    - name: SET_FACT | Set package from PHP version (manages PHP 7.x)
      set_fact: phalcon_package='php{{ phpversion.stdout }}-phalcon'
      when: phpversion.stdout.find('5') == -1

  when: >
    phalcon_package is none and
    not phpversion.failed
