---

- name: ASSERT | Check OS
  assert:
    that: ansible_distribution_release == 'jessie'

- name: APT_KEY | Get APT key repository
  apt_key: id=0x31F49B93 keyserver=pgp.mit.edu

- name: APT_REPOSITORY | Installs repository
  apt_repository: repo="{{ phalcon_apt }}"

- name: APT | Install Phalcon
  apt:
    pkg="{{ phalcon_package }}{% if phalcon_version is not none %}={{ phalcon_version }}{% endif %}"
    update_cache=yes
    cache_valid_time=3600
    state=present
