---

- name: SET_FACT | Bypass https://github.com/ansible/ansible/issues/19874
  set_fact:
    ansible_distribution_release: 'buster'
  when: ansible_facts.distribution_major_version == "buster/sid"

- name: IMPORT_TASKS | Install
  import_tasks: install.yml

- name: APT | Install Phalcon
  apt:
    pkg: "{{ phalcon_package }}{% if phalcon_version is not none %}={{ phalcon_version }}{% endif %}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
