---

- name: INCLUDE | Legacy install
  include: legacy.yml
  when: phalcon_legacy

- name: INCLUDE | Install
  include: install.yml
  when: not phalcon_legacy

- name: APT | Install Phalcon
  apt:
    pkg="{{ phalcon_package }}{% if phalcon_version is not none %}={{ phalcon_version }}{% endif %}"
    update_cache=yes
    cache_valid_time=3600
    state=present
